use crate::{Bar, CandleStore, Series, RcSeries};
use crate::NodeCache;
use crate::{rc_into_owned, nan_to_none};
use std::rc::Rc;
use std::collections::HashMap;
use crate::indicators::roc::{roc, roc_node, roc_store};

pub fn kst(bars: &[Bar]) -> Series {    let roc1 = roc(bars, 10);    let roc2 = roc(bars, 15);    let roc3 = roc(bars, 20);    let roc4 = roc(bars, 30);    let sma1 = sma_from_series(&roc1, 10);    let sma2 = sma_from_series(&roc2, 10);    let sma3 = sma_from_series(&roc3, 10);    let sma4 = sma_from_series(&roc4, 15);    sma1.iter()        .zip(sma2.iter())        .zip(sma3.iter())        .zip(sma4.iter())        .map(|(((a, b), c), d)| match (a, b, c, d) {            (a, b, c, d) if !a.is_nan() && !b.is_nan() && !c.is_nan() && !d.is_nan() => *a + 2.0 * *b + 3.0 * *c + 4.0 * *d,            _ => f64::NAN,        })        .collect()}
pub fn kst_node(bars: &[Bar], nodes: &mut NodeCache) -> Series {    let key = "kst:value".to_string();    if let Some(values) = nodes.get(&key) {        return (**values).clone();    }    let roc1 = roc_node(bars, 10, nodes);    let roc2 = roc_node(bars, 15, nodes);    let roc3 = roc_node(bars, 20, nodes);    let roc4 = roc_node(bars, 30, nodes);    let sma1 = sma_from_series(&roc1, 10);    let sma2 = sma_from_series(&roc2, 10);    let sma3 = sma_from_series(&roc3, 10);    let sma4 = sma_from_series(&roc4, 15);    let values: Vec<_> = sma1        .iter()        .zip(sma2.iter())        .zip(sma3.iter())        .zip(sma4.iter())        .map(|(((a, b), c), d)| match (a, b, c, d) {            (a, b, c, d) if !a.is_nan() && !b.is_nan() && !c.is_nan() && !d.is_nan() => *a + 2.0 * *b + 3.0 * *c + 4.0 * *d,            _ => f64::NAN,        })        .collect();    nodes.insert(key, Rc::new(values.clone()));    values}
pub fn kst_store(store: &CandleStore, nodes: &mut NodeCache) -> RcSeries {    let key = "kst:value".to_string();    if let Some(values) = nodes.get(&key) {        return Rc::clone(values);    }    let roc1 = roc_store(store, 10, nodes);    let roc2 = roc_store(store, 15, nodes);    let roc3 = roc_store(store, 20, nodes);    let roc4 = roc_store(store, 30, nodes);    let sma1 = sma_from_series(&roc1, 10);    let sma2 = sma_from_series(&roc2, 10);    let sma3 = sma_from_series(&roc3, 10);    let sma4 = sma_from_series(&roc4, 15);    let values: Vec<_> = sma1        .iter()        .zip(sma2.iter())        .zip(sma3.iter())        .zip(sma4.iter())        .map(|(((a, b), c), d)| match (a, b, c, d) {            (a, b, c, d) if !a.is_nan() && !b.is_nan() && !c.is_nan() && !d.is_nan() => *a + 2.0 * *b + 3.0 * *c + 4.0 * *d,            _ => f64::NAN,        })        .collect();    let rc = Rc::new(values); nodes.insert(key, Rc::clone(&rc));    rc}
pub fn latest_kst(bars: &[Bar]) -> Option<f64> {    kst(bars).last().copied().and_then(nan_to_none)}
pub fn latest_kst_store(store: &CandleStore) -> Option<f64> {    kst_store(store, &mut HashMap::new())        .last()        .copied().and_then(nan_to_none)}
pub fn sma_from_series(values: &[f64], period: usize) -> Series {    let mut out = vec![f64::NAN; values.len()];    if period == 0 || values.len() < period {        return out;    }    for index in period - 1..values.len() {        let window = &values[index + 1 - period..=index];        if window.iter().any(|value| value.is_nan()) {            continue;        }        out[index] = window.iter().sum::<f64>() / period as f64;    }    out}
