use crate::{Bar, CandleStore, Series, RcSeries};
use crate::NodeCache;
use crate::{rc_into_owned, nan_to_none};
use std::rc::Rc;
use crate::IndicatorOutput;
use crate::{output_at, output_at_vec};
use crate::IndicatorArena;
use crate::indicators::cci::{typical_price, typical_price_parts};

pub fn vwap(bars: &[Bar], nodes: &mut NodeCache) -> Vec<IndicatorOutput> {    if let Some(values) = nodes.get("vwap:hlcv") {        return vwap_outputs(            (**values).clone(),            nodes.get("vwap:cumulative_pv").map(|rc| (**rc).clone()).unwrap_or_default(),            nodes                .get("vwap:cumulative_volume")                .map(|rc| (**rc).clone())                .unwrap_or_default(),        );    }    let mut values = Vec::with_capacity(bars.len());    let mut cumulative_pv_values = Vec::with_capacity(bars.len());    let mut cumulative_volume_values = Vec::with_capacity(bars.len());    let mut cumulative_pv = 0.0;    let mut cumulative_volume = 0.0;    for bar in bars {        cumulative_pv += typical_price(bar) * bar.volume;        cumulative_volume += bar.volume;        values.push(if cumulative_volume > 0.0 { cumulative_pv / cumulative_volume } else { f64::NAN });        cumulative_pv_values.push(cumulative_pv);        cumulative_volume_values.push(cumulative_volume);    }    nodes.insert("vwap:hlcv".to_string(), Rc::new(values.clone()));    nodes.insert(        "vwap:cumulative_pv".to_string(),        Rc::new(cumulative_pv_values.clone()),    );    nodes.insert(        "vwap:cumulative_volume".to_string(),        Rc::new(cumulative_volume_values.clone()),    );    vwap_outputs(values, cumulative_pv_values, cumulative_volume_values)}
pub fn vwap_store(store: &CandleStore, nodes: &mut NodeCache) -> Vec<IndicatorOutput> {    if let Some(values) = nodes.get("vwap:hlcv") {        return vwap_outputs(            (**values).clone(),            nodes.get("vwap:cumulative_pv").map(|rc| (**rc).clone()).unwrap_or_default(),            nodes                .get("vwap:cumulative_volume")                .map(|rc| (**rc).clone())                .unwrap_or_default(),        );    }    let mut values = Vec::with_capacity(store.len());    let mut cumulative_pv_values = Vec::with_capacity(store.len());    let mut cumulative_volume_values = Vec::with_capacity(store.len());    let mut cumulative_pv = 0.0;    let mut cumulative_volume = 0.0;    for index in 0..store.len() {        cumulative_pv +=            typical_price_parts(store.high[index], store.low[index], store.close[index])                * store.volume[index];        cumulative_volume += store.volume[index];        values.push(if cumulative_volume > 0.0 { cumulative_pv / cumulative_volume } else { f64::NAN });        cumulative_pv_values.push(cumulative_pv);        cumulative_volume_values.push(cumulative_volume);    }    nodes.insert("vwap:hlcv".to_string(), Rc::new(values.clone()));    nodes.insert(        "vwap:cumulative_pv".to_string(),        Rc::new(cumulative_pv_values.clone()),    );    nodes.insert(        "vwap:cumulative_volume".to_string(),        Rc::new(cumulative_volume_values.clone()),    );    vwap_outputs(values, cumulative_pv_values, cumulative_volume_values)}
pub fn vwap_outputs(    values: Series,    cumulative_pv: Series,    cumulative_volume: Series,) -> Vec<IndicatorOutput> {    vec![        IndicatorOutput {            name: "value".to_string(),            values,        },        IndicatorOutput {            name: "cumulative_pv".to_string(),            values: cumulative_pv,        },        IndicatorOutput {            name: "cumulative_volume".to_string(),            values: cumulative_volume,        },    ]}
pub fn latest_vwap(    bars: &[Bar],    outputs: &IndicatorArena,) -> (Option<f64>, Option<f64>, Option<f64>) {    let Some(last) = bars.last() else {        return (None, None, None);    };    let previous_index = bars.len().checked_sub(2);    let previous_pv = previous_index        .and_then(|index| output_at(outputs, "cumulative_pv", index))        .unwrap_or(0.0);    let previous_volume = previous_index        .and_then(|index| output_at(outputs, "cumulative_volume", index))        .unwrap_or(0.0);    let cumulative_pv = previous_pv + typical_price(last) * last.volume;    let cumulative_volume = previous_volume + last.volume;    (        (cumulative_volume > 0.0).then_some(cumulative_pv / cumulative_volume),        Some(cumulative_pv),        Some(cumulative_volume),    )}
pub fn latest_vwap_store(    store: &CandleStore,    outputs: &IndicatorArena,) -> (Option<f64>, Option<f64>, Option<f64>) {    let Some(index) = store.len().checked_sub(1) else {        return (None, None, None);    };    let previous_index = index.checked_sub(1);    let previous_pv = previous_index        .and_then(|previous_index| output_at(outputs, "cumulative_pv", previous_index))        .unwrap_or(0.0);    let previous_volume = previous_index        .and_then(|previous_index| output_at(outputs, "cumulative_volume", previous_index))        .unwrap_or(0.0);    let cumulative_pv = previous_pv        + typical_price_parts(store.high[index], store.low[index], store.close[index])            * store.volume[index];    let cumulative_volume = previous_volume + store.volume[index];    (        (cumulative_volume > 0.0).then_some(cumulative_pv / cumulative_volume),        Some(cumulative_pv),        Some(cumulative_volume),    )}
