use crate::{Bar, CandleStore, Series, RcSeries};
use crate::NodeCache;
use crate::{rc_into_owned, nan_to_none};
use std::rc::Rc;

pub fn williams_r(bars: &[Bar], period: usize) -> Series {    let mut out = vec![f64::NAN; bars.len()];    if period == 0 || bars.len() < period {        return out;    }    for index in period - 1..bars.len() {        let window = &bars[index + 1 - period..=index];        let highest_high = window.iter().map(|bar| bar.high).fold(f64::MIN, f64::max);        let lowest_low = window.iter().map(|bar| bar.low).fold(f64::MAX, f64::min);        let range = highest_high - lowest_low;        out[index] = if range == 0.0 { 0.0 } else { -100.0 * (highest_high - bars[index].close) / range };    }    out}
pub fn williams_r_node(bars: &[Bar], period: usize, nodes: &mut NodeCache) -> Series {    let key = format!("willr:hlc:{period}");    if let Some(values) = nodes.get(&key) {        return (**values).clone();    }    let values = williams_r(bars, period);    nodes.insert(key, Rc::new(values.clone()));    values}
pub fn williams_r_store(store: &CandleStore, period: usize, nodes: &mut NodeCache) -> RcSeries {    let key = format!("willr:hlc:{period}");    if let Some(values) = nodes.get(&key) {        return Rc::clone(values);    }    let mut out = vec![f64::NAN; store.len()];    if period == 0 || store.len() < period {        let rc = Rc::new(out); nodes.insert(key, Rc::clone(&rc));        return rc;    }    for index in period - 1..store.len() {        let window = index + 1 - period..=index;        let highest_high = window            .clone()            .map(|i| store.high[i])            .fold(f64::MIN, f64::max);        let lowest_low = window.map(|i| store.low[i]).fold(f64::MAX, f64::min);        let range = highest_high - lowest_low;        out[index] = if range == 0.0 { 0.0 } else { -100.0 * (highest_high - store.close[index]) / range };    }    let rc = Rc::new(out); nodes.insert(key, Rc::clone(&rc));    rc}
pub fn latest_williams_r(bars: &[Bar], period: usize) -> Option<f64> {    if period == 0 || bars.len() < period {        return None;    }    let window = &bars[bars.len() - period..];    let highest_high = window.iter().map(|bar| bar.high).fold(f64::MIN, f64::max);    let lowest_low = window.iter().map(|bar| bar.low).fold(f64::MAX, f64::min);    let range = highest_high - lowest_low;    Some(if range == 0.0 {        0.0    } else {        -100.0 * (highest_high - bars.last().expect("checked non-empty").close) / range    })}
pub fn latest_williams_r_store(store: &CandleStore, period: usize) -> Option<f64> {    if period == 0 || store.len() < period {        return None;    }    let start = store.len() - period;    let highest_high = store.high[start..].iter().copied().fold(f64::MIN, f64::max);    let lowest_low = store.low[start..].iter().copied().fold(f64::MAX, f64::min);    let range = highest_high - lowest_low;    Some(if range == 0.0 {        0.0    } else {        -100.0 * (highest_high - store.close[store.len() - 1]) / range    })}
