use crate::{Bar, CandleStore, Series, RcSeries};
use crate::NodeCache;
use crate::{rc_into_owned, nan_to_none};
use std::rc::Rc;

pub fn williams_ad(bars: &[Bar]) -> Series {    let mut out = Vec::with_capacity(bars.len());    let mut current = 0.0;    for (index, bar) in bars.iter().enumerate() {        if index > 0 {            current += williams_ad_step(bars[index - 1].close, bar);        }        out.push(current);    }    out}
pub fn williams_ad_step(previous_close: f64, bar: &Bar) -> f64 {    williams_ad_step_parts(previous_close, bar.high, bar.low, bar.close)}
pub fn williams_ad_step_parts(previous_close: f64, high: f64, low: f64, close: f64) -> f64 {    if close > previous_close {        close - previous_close.min(low)    } else if close < previous_close {        close - previous_close.max(high)    } else {        0.0    }}
pub fn williams_ad_node(bars: &[Bar], nodes: &mut NodeCache) -> Series {    let key = "wad:ohlc".to_string();    if let Some(values) = nodes.get(&key) {        return (**values).clone();    }    let values = williams_ad(bars);    nodes.insert(key, Rc::new(values.clone()));    values}
pub fn williams_ad_store(store: &CandleStore, nodes: &mut NodeCache) -> RcSeries {    let key = "wad:ohlc".to_string();    if let Some(values) = nodes.get(&key) {        return Rc::clone(values);    }    let mut out = Vec::with_capacity(store.len());    let mut current = 0.0;    for index in 0..store.len() {        if index > 0 {            current += williams_ad_step_parts(                store.close[index - 1],                store.high[index],                store.low[index],                store.close[index],            );        }        out.push(current);    }    let rc = Rc::new(out); nodes.insert(key, Rc::clone(&rc));    rc}
pub fn latest_williams_ad(bars: &[Bar], output: Option<&[f64]>) -> Option<f64> {    let last = bars.last()?;    if bars.len() == 1 {        return Some(0.0);    }    let previous = bars        .len()        .checked_sub(2)        .and_then(|index| {            output                .and_then(|values| values.get(index))                .copied().and_then(nan_to_none)        })        .unwrap_or(0.0);    Some(previous + williams_ad_step(bars[bars.len() - 2].close, last))}
pub fn latest_williams_ad_store(store: &CandleStore, output: Option<&[f64]>) -> Option<f64> {    let index = store.len().checked_sub(1)?;    if index == 0 {        return Some(0.0);    }    let previous = output        .and_then(|values| values.get(index - 1))        .copied().and_then(nan_to_none)        .unwrap_or(0.0);    Some(        previous            + williams_ad_step_parts(                store.close[index - 1],                store.high[index],                store.low[index],                store.close[index],            ),    )}
