use serde::Serialize;

#[derive(Serialize)]
pub(crate) struct IndicatorDescriptor {
    pub kind: &'static str,
    pub name: &'static str,
    pub category: &'static str,
    pub pane: &'static str,
    pub params: Vec<ParamDescriptor>,
    pub outputs: Vec<OutputDescriptor>,
}

#[derive(Serialize)]
pub(crate) struct ParamDescriptor {
    pub name: &'static str,
    pub label: &'static str,
    pub default: f64,
    pub min: f64,
    pub step: &'static str,
}

#[derive(Serialize)]
pub(crate) struct OutputDescriptor {
    pub name: &'static str,
    pub renderer: &'static str,
    pub pane: &'static str,
    pub color: &'static str,
}

pub(crate) fn period_descriptor(
    kind: &'static str,
    name: &'static str,
    category: &'static str,
    pane: &'static str,
    default: usize,
) -> IndicatorDescriptor {
    IndicatorDescriptor {
        kind,
        name,
        category,
        pane,
        params: vec![ParamDescriptor {
            name: "period",
            label: "Period",
            default: default as f64,
            min: 1.0,
            step: "1",
        }],
        outputs: vec![output_descriptor("value", "line", pane, "#2563eb")],
    }
}

pub(crate) fn output_descriptor(
    name: &'static str,
    renderer: &'static str,
    pane: &'static str,
    color: &'static str,
) -> OutputDescriptor {
    OutputDescriptor {
        name,
        renderer,
        pane,
        color,
    }
}

pub(crate) fn indicator_descriptors() -> Vec<IndicatorDescriptor> {
    vec![
        crate::indicators::sma::descriptor(),
        crate::indicators::ema::descriptor(),
        crate::indicators::wma::descriptor(),
        crate::indicators::hma::descriptor(),
        crate::indicators::linear_regression::descriptor(),
        crate::indicators::dema::descriptor(),
        crate::indicators::tema::descriptor(),
        crate::indicators::trima::descriptor(),
        crate::indicators::stddev::descriptor(),
        crate::indicators::trix::descriptor(),
        crate::indicators::envelope::descriptor(),
        crate::indicators::tsi::descriptor(),
        crate::indicators::dpo::descriptor(),
        crate::indicators::momentum::descriptor(),
        crate::indicators::rsi::descriptor(),
        crate::indicators::roc::descriptor(),
        crate::indicators::cci::descriptor(),
        crate::indicators::mfi::descriptor(),
        crate::indicators::cmf::descriptor(),
        crate::indicators::force_index::descriptor(),
        crate::indicators::vwma::descriptor(),
        crate::indicators::williams_ad::descriptor(),
        crate::indicators::chaikin::chaikin_volatility_descriptor(),
        crate::indicators::donchian::price_channel_descriptor(),
        crate::indicators::keltner::starc_descriptor(),
        crate::indicators::williams_r::descriptor(),
        crate::indicators::parabolic_sar::descriptor(),
        crate::indicators::ichimoku::descriptor(),
        crate::indicators::pivot_points::descriptor(),
        crate::indicators::aroon::descriptor(),
        crate::indicators::adl::descriptor(),
        crate::indicators::kst::descriptor(),
        crate::indicators::bop::descriptor(),
        crate::indicators::ultimate_oscillator::descriptor(),
        crate::indicators::supertrend::descriptor(),
        crate::indicators::keltner::keltner_descriptor(),
        crate::indicators::donchian::donchian_descriptor(),
        crate::indicators::stoch_rsi::descriptor(),
        crate::indicators::atr::descriptor(),
        crate::indicators::adx::descriptor(),
        crate::indicators::vwap::descriptor(),
        crate::indicators::stoch::descriptor(),
        crate::indicators::obv::descriptor(),
        crate::indicators::bollinger::descriptor(),
        crate::indicators::macd::macd_descriptor(),
        crate::indicators::macd::ppo_descriptor(),
        crate::indicators::chaikin::chaikin_oscillator_descriptor(),
        crate::indicators::median_price::descriptor(),
        crate::indicators::highest_high::descriptor(),
        crate::indicators::lowest_low::descriptor(),
        crate::indicators::alligator::descriptor(),
        crate::indicators::atr_bands::descriptor(),
        crate::indicators::high_low_bands::descriptor(),
        crate::indicators::fractal_chaos_bands::descriptor(),
        crate::indicators::gmma::descriptor(),
        crate::indicators::linear_reg_forecast::descriptor(),
        crate::indicators::linear_reg_intercept::descriptor(),
        crate::indicators::anchored_vwap::descriptor(),
        crate::indicators::typical_price::descriptor(),
        crate::indicators::weighted_close::descriptor(),
        crate::indicators::ma_cross::descriptor(),
        crate::indicators::rainbow_ma::descriptor(),
        crate::indicators::prime_number_bands::descriptor(),
        crate::indicators::linear_reg_forecast::time_series_forecast_descriptor(),
        crate::indicators::valuation_lines::descriptor(),
        crate::indicators::beta::descriptor(),
        crate::indicators::correlation_coefficient::descriptor(),
        crate::indicators::performance_index::descriptor(),
        crate::indicators::price_relative::descriptor(),
        crate::indicators::awesome_oscillator::descriptor(),
        crate::indicators::bollinger_pct_b::descriptor(),
        crate::indicators::center_of_gravity::descriptor(),
        crate::indicators::chande_forecast::descriptor(),
        crate::indicators::chande_momentum::descriptor(),
        crate::indicators::coppock_curve::descriptor(),
        crate::indicators::disparity_index::descriptor(),
        crate::indicators::ease_of_movement::descriptor(),
        crate::indicators::ehler_fisher::descriptor(),
        crate::indicators::elder_ray::descriptor(),
        crate::indicators::fractal_chaos_oscillator::descriptor(),
        crate::indicators::gator_oscillator::descriptor(),
        crate::indicators::intraday_momentum::descriptor(),
        crate::indicators::linear_reg_slope::descriptor(),
        crate::indicators::ma_deviation::descriptor(),
        crate::indicators::pretty_good_oscillator::descriptor(),
        crate::indicators::price_momentum_oscillator::descriptor(),
        crate::indicators::price_oscillator::descriptor(),
        crate::indicators::rainbow_oscillator::descriptor(),
        crate::indicators::ravi::descriptor(),
        crate::indicators::relative_vigor::descriptor(),
        crate::indicators::schaff_trend_cycle::descriptor(),
        crate::indicators::stochastic_momentum::descriptor(),
        crate::indicators::swing_index::descriptor(),
        crate::indicators::trend_intensity::descriptor(),
        crate::indicators::volume_oscillator::descriptor(),
        crate::indicators::klinger_volume::descriptor(),
        crate::indicators::market_facilitation::descriptor(),
        crate::indicators::negative_volume_index::descriptor(),
        crate::indicators::positive_volume_index::descriptor(),
        crate::indicators::price_volume_trend::descriptor(),
        crate::indicators::trade_volume_index::descriptor(),
        crate::indicators::twiggs_money_flow::descriptor(),
        crate::indicators::projected_aggregate_volume::descriptor(),
        crate::indicators::projected_volume_at_time::descriptor(),
        crate::indicators::historical_volatility::descriptor(),
        crate::indicators::linear_reg_r2::descriptor(),
        crate::indicators::prime_number_oscillator::descriptor(),
        crate::indicators::random_walk_index::descriptor(),
        crate::indicators::darvas_box::descriptor(),
        crate::indicators::volume_profile::descriptor(),
        crate::indicators::choppiness_index::descriptor(),
        crate::indicators::elder_impulse::descriptor(),
        crate::indicators::gonogo_trend::descriptor(),
        crate::indicators::psychological_line::descriptor(),
        crate::indicators::qstick::descriptor(),
        crate::indicators::shinohara_intensity::descriptor(),
        crate::indicators::ulcer_index::descriptor(),
        crate::indicators::vertical_horizontal_filter::descriptor(),
        crate::indicators::vortex_indicator::descriptor(),
        crate::indicators::zigzag::descriptor(),
        crate::indicators::bollinger_bandwidth::descriptor(),
        crate::indicators::donchian_width::descriptor(),
        crate::indicators::gopalakrishnan_range::descriptor(),
        crate::indicators::high_minus_low::descriptor(),
        crate::indicators::mass_index::descriptor(),
        crate::indicators::relative_volatility::descriptor(),
        crate::indicators::true_range::descriptor(),
        crate::indicators::volume_chart::descriptor(),
        crate::indicators::volume_roc::descriptor(),
        crate::indicators::volume_underlay::descriptor(),
    ]
}
