use serde::Serialize;

#[derive(Serialize)]
pub(crate) struct IndicatorDescriptor {
    pub kind: &'static str,
    pub name: &'static str,
    pub category: &'static str,
    pub pane: &'static str,
    pub params: Vec<ParamDescriptor>,
    pub outputs: Vec<OutputDescriptor>,
}

#[derive(Serialize)]
pub(crate) struct ParamDescriptor {
    pub name: &'static str,
    pub label: &'static str,
    pub default: f64,
    pub min: f64,
    pub step: &'static str,
}

#[derive(Serialize)]
pub(crate) struct OutputDescriptor {
    pub name: &'static str,
    pub renderer: &'static str,
    pub pane: &'static str,
    pub color: &'static str,
}

pub(crate) fn period_descriptor(
    kind: &'static str,
    name: &'static str,
    category: &'static str,
    pane: &'static str,
    default: usize,
) -> IndicatorDescriptor {
    IndicatorDescriptor {
        kind,
        name,
        category,
        pane,
        params: vec![ParamDescriptor {
            name: "period",
            label: "Period",
            default: default as f64,
            min: 1.0,
            step: "1",
        }],
        outputs: vec![output_descriptor("value", "line", pane, "#2563eb")],
    }
}

pub(crate) fn output_descriptor(
    name: &'static str,
    renderer: &'static str,
    pane: &'static str,
    color: &'static str,
) -> OutputDescriptor {
    OutputDescriptor {
        name,
        renderer,
        pane,
        color,
    }
}

pub(crate) fn indicator_descriptors() -> Vec<IndicatorDescriptor> {
    vec![
        period_descriptor("SMA", "SMA", "Moving Average", "overlay", 20),
        period_descriptor("EMA", "EMA", "Moving Average", "overlay", 20),
        period_descriptor("WMA", "WMA", "Moving Average", "overlay", 20),
        period_descriptor("HMA", "HMA", "Moving Average", "overlay", 20),
        period_descriptor("LINEAR_REGRESSION", "LINEAR REGRESSION", "Projection", "overlay", 20),
        period_descriptor("DEMA", "DEMA", "Moving Average", "overlay", 20),
        period_descriptor("TEMA", "TEMA", "Moving Average", "overlay", 20),
        period_descriptor("TRIMA", "TRIMA", "Moving Average", "overlay", 20),
        period_descriptor("STDDEV", "STDDEV", "Statistical", "separate", 20),
        period_descriptor("TRIX", "TRIX", "Momentum/Oscillator", "separate", 15),
        IndicatorDescriptor {
            kind: "ENVELOPE",
            name: "ENVELOPE",
            category: "Averages/Bands",
            pane: "overlay",
            params: vec![
                ParamDescriptor {
                    name: "period",
                    label: "Period",
                    default: 20.0,
                    min: 1.0,
                    step: "1",
                },
                ParamDescriptor {
                    name: "multiplier",
                    label: "Multiplier %",
                    default: 2.0,
                    min: 0.1,
                    step: "0.1",
                },
            ],
            outputs: vec![
                output_descriptor("upper", "line", "overlay", "#2563eb"),
                output_descriptor("middle", "line", "overlay", "#64748b"),
                output_descriptor("lower", "line", "overlay", "#dc2626"),
            ],
        },
        IndicatorDescriptor {
            kind: "TSI",
            name: "TSI",
            category: "Momentum/Oscillator",
            pane: "separate",
            params: vec![
                ParamDescriptor {
                    name: "period",
                    label: "Long",
                    default: 25.0,
                    min: 1.0,
                    step: "1",
                },
                ParamDescriptor {
                    name: "stoch_period",
                    label: "Short",
                    default: 13.0,
                    min: 1.0,
                    step: "1",
                },
            ],
            outputs: vec![output_descriptor("value", "line", "separate", "#2563eb")],
        },
        period_descriptor("DPO", "DPO", "Momentum/Oscillator", "separate", 20),
        period_descriptor("MOMENTUM", "MOMENTUM", "Momentum/Oscillator", "separate", 10),
        period_descriptor("RSI", "RSI", "Momentum/Oscillator", "separate", 14),
        period_descriptor("ROC", "ROC", "Momentum/Oscillator", "separate", 14),
        period_descriptor("CCI", "CCI", "Momentum/Oscillator", "separate", 20),
        period_descriptor("MFI", "MFI", "Money Flow", "separate", 14),
        period_descriptor("CMF", "CMF", "Money Flow", "separate", 20),
        period_descriptor("FORCE_INDEX", "FORCE INDEX", "Money Flow", "separate", 13),
        period_descriptor("VWMA", "VWMA", "Moving Average", "overlay", 20),
        IndicatorDescriptor {
            kind: "WILLIAMS_AD",
            name: "WILLIAMS A/D",
            category: "Volume",
            pane: "separate",
            params: Vec::new(),
            outputs: vec![output_descriptor("value", "line", "separate", "#9333ea")],
        },
        period_descriptor("CHAIKIN_VOLATILITY", "CHAIKIN VOLATILITY", "Volatility", "separate", 10),
        IndicatorDescriptor {
            kind: "PRICE_CHANNEL",
            name: "PRICE CHANNEL",
            category: "Support/Resistance",
            pane: "overlay",
            params: vec![ParamDescriptor {
                name: "period",
                label: "Period",
                default: 20.0,
                min: 1.0,
                step: "1",
            }],
            outputs: vec![
                output_descriptor("upper", "line", "overlay", "#f59e0b"),
                output_descriptor("middle", "line", "overlay", "#64748b"),
                output_descriptor("lower", "line", "overlay", "#f59e0b"),
            ],
        },
        IndicatorDescriptor {
            kind: "STARC",
            name: "STARC",
            category: "Averages/Bands",
            pane: "overlay",
            params: vec![
                ParamDescriptor {
                    name: "period",
                    label: "Period",
                    default: 15.0,
                    min: 1.0,
                    step: "1",
                },
                ParamDescriptor {
                    name: "multiplier",
                    label: "Multiplier",
                    default: 2.0,
                    min: 0.1,
                    step: "0.1",
                },
            ],
            outputs: vec![
                output_descriptor("upper", "line", "overlay", "#0f766e"),
                output_descriptor("middle", "line", "overlay", "#2563eb"),
                output_descriptor("lower", "line", "overlay", "#0f766e"),
            ],
        },
        period_descriptor("WILLIAMS_R", "WILLIAMS %R", "Momentum/Oscillator", "separate", 14),
        IndicatorDescriptor {
            kind: "PARABOLIC_SAR",
            name: "PARABOLIC SAR",
            category: "Support/Resistance",
            pane: "overlay",
            params: vec![
                ParamDescriptor {
                    name: "psar_step",
                    label: "Step",
                    default: 0.02,
                    min: 0.001,
                    step: "0.001",
                },
                ParamDescriptor {
                    name: "psar_max_step",
                    label: "Max",
                    default: 0.2,
                    min: 0.01,
                    step: "0.01",
                },
            ],
            outputs: vec![output_descriptor("value", "line", "overlay", "#059669")],
        },
        IndicatorDescriptor {
            kind: "ICHIMOKU",
            name: "ICHIMOKU",
            category: "Projection",
            pane: "overlay",
            params: vec![
                ParamDescriptor {
                    name: "tenkan_period",
                    label: "Tenkan",
                    default: 9.0,
                    min: 1.0,
                    step: "1",
                },
                ParamDescriptor {
                    name: "kijun_period",
                    label: "Kijun",
                    default: 26.0,
                    min: 1.0,
                    step: "1",
                },
                ParamDescriptor {
                    name: "senkou_b_period",
                    label: "Senkou B",
                    default: 52.0,
                    min: 1.0,
                    step: "1",
                },
            ],
            outputs: vec![
                output_descriptor("tenkan", "line", "overlay", "#2563eb"),
                output_descriptor("kijun", "line", "overlay", "#dc2626"),
                output_descriptor("senkou_a", "line", "overlay", "#059669"),
                output_descriptor("senkou_b", "line", "overlay", "#ea580c"),
                output_descriptor("chikou", "line", "overlay", "#64748b"),
            ],
        },
        IndicatorDescriptor {
            kind: "PIVOT_POINTS",
            name: "PIVOT POINTS",
            category: "Support/Resistance",
            pane: "overlay",
            params: Vec::new(),
            outputs: vec![
                output_descriptor("pp", "line", "overlay", "#64748b"),
                output_descriptor("r1", "line", "overlay", "#059669"),
                output_descriptor("s1", "line", "overlay", "#dc2626"),
                output_descriptor("r2", "line", "overlay", "#16a34a"),
                output_descriptor("s2", "line", "overlay", "#b91c1c"),
            ],
        },
        IndicatorDescriptor {
            kind: "AROON",
            name: "AROON",
            category: "Trend Analysis",
            pane: "separate",
            params: vec![ParamDescriptor {
                name: "period",
                label: "Period",
                default: 14.0,
                min: 1.0,
                step: "1",
            }],
            outputs: vec![
                output_descriptor("up", "line", "separate", "#059669"),
                output_descriptor("down", "line", "separate", "#dc2626"),
                output_descriptor("oscillator", "line", "separate", "#2563eb"),
            ],
        },
        IndicatorDescriptor {
            kind: "ADL",
            name: "ADL",
            category: "Volume",
            pane: "separate",
            params: Vec::new(),
            outputs: vec![output_descriptor("value", "line", "separate", "#9333ea")],
        },
        IndicatorDescriptor {
            kind: "KST",
            name: "KST",
            category: "Momentum/Oscillator",
            pane: "separate",
            params: Vec::new(),
            outputs: vec![output_descriptor("value", "line", "separate", "#2563eb")],
        },
        IndicatorDescriptor {
            kind: "BOP",
            name: "BOP",
            category: "Momentum/Oscillator",
            pane: "separate",
            params: Vec::new(),
            outputs: vec![output_descriptor("value", "line", "separate", "#9333ea")],
        },
        IndicatorDescriptor {
            kind: "ULTIMATE_OSCILLATOR",
            name: "ULTIMATE OSCILLATOR",
            category: "Momentum/Oscillator",
            pane: "separate",
            params: vec![
                ParamDescriptor {
                    name: "period",
                    label: "Short",
                    default: 7.0,
                    min: 1.0,
                    step: "1",
                },
                ParamDescriptor {
                    name: "stoch_period",
                    label: "Medium",
                    default: 14.0,
                    min: 1.0,
                    step: "1",
                },
                ParamDescriptor {
                    name: "smooth",
                    label: "Long",
                    default: 28.0,
                    min: 1.0,
                    step: "1",
                },
            ],
            outputs: vec![output_descriptor("value", "line", "separate", "#2563eb")],
        },
        IndicatorDescriptor {
            kind: "SUPERTREND",
            name: "SUPERTREND",
            category: "Support/Resistance",
            pane: "overlay",
            params: vec![
                ParamDescriptor {
                    name: "period",
                    label: "Period",
                    default: 10.0,
                    min: 1.0,
                    step: "1",
                },
                ParamDescriptor {
                    name: "multiplier",
                    label: "Multiplier",
                    default: 3.0,
                    min: 1.0,
                    step: "0.1",
                },
            ],
            outputs: vec![output_descriptor("value", "line", "overlay", "#0f766e")],
        },
        IndicatorDescriptor {
            kind: "KELTNER",
            name: "KELTNER",
            category: "Averages/Bands",
            pane: "overlay",
            params: vec![
                ParamDescriptor {
                    name: "period",
                    label: "Period",
                    default: 20.0,
                    min: 1.0,
                    step: "1",
                },
                ParamDescriptor {
                    name: "multiplier",
                    label: "Multiplier",
                    default: 2.0,
                    min: 1.0,
                    step: "0.1",
                },
            ],
            outputs: vec![
                output_descriptor("upper", "line", "overlay", "#0f766e"),
                output_descriptor("middle", "line", "overlay", "#2563eb"),
                output_descriptor("lower", "line", "overlay", "#0f766e"),
            ],
        },
        IndicatorDescriptor {
            kind: "DONCHIAN",
            name: "DONCHIAN",
            category: "Averages/Bands",
            pane: "overlay",
            params: vec![ParamDescriptor {
                name: "period",
                label: "Period",
                default: 20.0,
                min: 1.0,
                step: "1",
            }],
            outputs: vec![
                output_descriptor("upper", "line", "overlay", "#f59e0b"),
                output_descriptor("middle", "line", "overlay", "#64748b"),
                output_descriptor("lower", "line", "overlay", "#f59e0b"),
            ],
        },
        IndicatorDescriptor {
            kind: "STOCH_RSI",
            name: "STOCH RSI",
            category: "Momentum/Oscillator",
            pane: "separate",
            params: vec![
                ParamDescriptor {
                    name: "period",
                    label: "Period",
                    default: 14.0,
                    min: 1.0,
                    step: "1",
                },
                ParamDescriptor {
                    name: "stoch_period",
                    label: "Stoch",
                    default: 14.0,
                    min: 1.0,
                    step: "1",
                },
                ParamDescriptor {
                    name: "smooth",
                    label: "%K",
                    default: 3.0,
                    min: 1.0,
                    step: "1",
                },
                ParamDescriptor {
                    name: "signal",
                    label: "%D",
                    default: 3.0,
                    min: 1.0,
                    step: "1",
                },
            ],
            outputs: vec![
                output_descriptor("k", "line", "separate", "#2563eb"),
                output_descriptor("d", "line", "separate", "#dc2626"),
            ],
        },
        period_descriptor("ATR", "ATR", "Volatility", "separate", 14),
        IndicatorDescriptor {
            kind: "ADX",
            name: "ADX",
            category: "Trend Analysis",
            pane: "separate",
            params: vec![ParamDescriptor {
                name: "period",
                label: "Period",
                default: 14.0,
                min: 1.0,
                step: "1",
            }],
            outputs: vec![
                output_descriptor("value", "line", "separate", "#2563eb"),
                output_descriptor("plus_di", "line", "separate", "#059669"),
                output_descriptor("minus_di", "line", "separate", "#dc2626"),
            ],
        },
        IndicatorDescriptor {
            kind: "VWAP",
            name: "VWAP",
            category: "Volume",
            pane: "overlay",
            params: Vec::new(),
            outputs: vec![output_descriptor("value", "line", "overlay", "#0f766e")],
        },
        IndicatorDescriptor {
            kind: "STOCHASTIC",
            name: "STOCHASTIC",
            category: "Momentum/Oscillator",
            pane: "separate",
            params: vec![
                ParamDescriptor {
                    name: "period",
                    label: "Period",
                    default: 14.0,
                    min: 1.0,
                    step: "1",
                },
                ParamDescriptor {
                    name: "smooth",
                    label: "Smooth",
                    default: 3.0,
                    min: 1.0,
                    step: "1",
                },
            ],
            outputs: vec![
                output_descriptor("k", "line", "separate", "#2563eb"),
                output_descriptor("d", "line", "separate", "#dc2626"),
            ],
        },
        IndicatorDescriptor {
            kind: "OBV",
            name: "OBV",
            category: "Volume",
            pane: "separate",
            params: Vec::new(),
            outputs: vec![output_descriptor("value", "line", "separate", "#059669")],
        },
        IndicatorDescriptor {
            kind: "BB",
            name: "BOLLINGER",
            category: "Averages/Bands",
            pane: "overlay",
            params: vec![
                ParamDescriptor {
                    name: "period",
                    label: "Period",
                    default: 20.0,
                    min: 1.0,
                    step: "1",
                },
                ParamDescriptor {
                    name: "multiplier",
                    label: "Multiplier",
                    default: 2.0,
                    min: 1.0,
                    step: "0.1",
                },
            ],
            outputs: vec![
                output_descriptor("upper", "line", "overlay", "#9333ea"),
                output_descriptor("middle", "line", "overlay", "#64748b"),
                output_descriptor("lower", "line", "overlay", "#9333ea"),
            ],
        },
        IndicatorDescriptor {
            kind: "MACD",
            name: "MACD",
            category: "Momentum/Oscillator",
            pane: "separate",
            params: vec![
                ParamDescriptor {
                    name: "fast",
                    label: "Fast",
                    default: 12.0,
                    min: 1.0,
                    step: "1",
                },
                ParamDescriptor {
                    name: "slow",
                    label: "Slow",
                    default: 26.0,
                    min: 2.0,
                    step: "1",
                },
                ParamDescriptor {
                    name: "signal",
                    label: "Signal",
                    default: 9.0,
                    min: 1.0,
                    step: "1",
                },
            ],
            outputs: vec![
                output_descriptor("macd", "line", "separate", "#2563eb"),
                output_descriptor("signal", "line", "separate", "#dc2626"),
                output_descriptor("histogram", "histogram", "separate", "#86efac"),
            ],
        },
        IndicatorDescriptor {
            kind: "PPO",
            name: "PPO",
            category: "Momentum/Oscillator",
            pane: "separate",
            params: vec![
                ParamDescriptor {
                    name: "fast",
                    label: "Fast",
                    default: 12.0,
                    min: 1.0,
                    step: "1",
                },
                ParamDescriptor {
                    name: "slow",
                    label: "Slow",
                    default: 26.0,
                    min: 2.0,
                    step: "1",
                },
                ParamDescriptor {
                    name: "signal",
                    label: "Signal",
                    default: 9.0,
                    min: 1.0,
                    step: "1",
                },
            ],
            outputs: vec![
                output_descriptor("ppo", "line", "separate", "#2563eb"),
                output_descriptor("signal", "line", "separate", "#dc2626"),
                output_descriptor("histogram", "histogram", "separate", "#86efac"),
            ],
        },
        IndicatorDescriptor {
            kind: "CHAIKIN_OSCILLATOR",
            name: "CHAIKIN OSCILLATOR",
            category: "Money Flow",
            pane: "separate",
            params: vec![
                ParamDescriptor {
                    name: "fast",
                    label: "Fast",
                    default: 3.0,
                    min: 1.0,
                    step: "1",
                },
                ParamDescriptor {
                    name: "slow",
                    label: "Slow",
                    default: 10.0,
                    min: 2.0,
                    step: "1",
                },
            ],
            outputs: vec![output_descriptor("value", "line", "separate", "#9333ea")],
        },
        // ─── New indicators ──────────────────────────────────────────
        IndicatorDescriptor {
            kind: "MEDIAN_PRICE",
            name: "MEDIAN PRICE",
            category: "Statistical",
            pane: "overlay",
            params: Vec::new(),
            outputs: vec![output_descriptor("value", "line", "overlay", "#64748b")],
        },
        period_descriptor("HIGHEST_HIGH", "HIGHEST HIGH VALUE", "Statistical", "overlay", 14),
        period_descriptor("LOWEST_LOW", "LOWEST LOW VALUE", "Statistical", "overlay", 14),
        IndicatorDescriptor {
            kind: "ALLIGATOR",
            name: "ALLIGATOR",
            category: "Averages/Bands",
            pane: "overlay",
            params: Vec::new(),
            outputs: vec![
                output_descriptor("jaw", "line", "overlay", "#2563eb"),
                output_descriptor("teeth", "line", "overlay", "#dc2626"),
                output_descriptor("lips", "line", "overlay", "#059669"),
            ],
        },
        IndicatorDescriptor {
            kind: "ATR_BANDS",
            name: "ATR BANDS",
            category: "Averages/Bands",
            pane: "overlay",
            params: vec![
                ParamDescriptor {
                    name: "period",
                    label: "Period",
                    default: 14.0,
                    min: 1.0,
                    step: "1",
                },
                ParamDescriptor {
                    name: "multiplier",
                    label: "Multiplier",
                    default: 2.0,
                    min: 0.1,
                    step: "0.1",
                },
            ],
            outputs: vec![
                output_descriptor("upper", "line", "overlay", "#0f766e"),
                output_descriptor("middle", "line", "overlay", "#2563eb"),
                output_descriptor("lower", "line", "overlay", "#0f766e"),
            ],
        },
        IndicatorDescriptor {
            kind: "HIGH_LOW_BANDS",
            name: "HIGH LOW BANDS",
            category: "Statistical",
            pane: "overlay",
            params: vec![ParamDescriptor {
                name: "period",
                label: "Period",
                default: 14.0,
                min: 1.0,
                step: "1",
            }],
            outputs: vec![
                output_descriptor("upper", "line", "overlay", "#f59e0b"),
                output_descriptor("middle", "line", "overlay", "#64748b"),
                output_descriptor("lower", "line", "overlay", "#f59e0b"),
            ],
        },
        IndicatorDescriptor {
            kind: "FRACTAL_CHAOS_BANDS",
            name: "FRACTAL CHAOS BANDS",
            category: "Averages/Bands",
            pane: "overlay",
            params: Vec::new(),
            outputs: vec![
                output_descriptor("upper", "line", "overlay", "#9333ea"),
                output_descriptor("lower", "line", "overlay", "#9333ea"),
            ],
        },
        IndicatorDescriptor {
            kind: "GMMA",
            name: "GUPPY MULTIPLE MOVING AVERAGE",
            category: "Averages/Bands",
            pane: "overlay",
            params: Vec::new(),
            outputs: vec![
                output_descriptor("short_3", "line", "overlay", "#059669"),
                output_descriptor("short_5", "line", "overlay", "#059669"),
                output_descriptor("short_8", "line", "overlay", "#059669"),
                output_descriptor("short_10", "line", "overlay", "#059669"),
                output_descriptor("short_12", "line", "overlay", "#059669"),
                output_descriptor("short_15", "line", "overlay", "#059669"),
                output_descriptor("long_30", "line", "overlay", "#dc2626"),
                output_descriptor("long_35", "line", "overlay", "#dc2626"),
                output_descriptor("long_40", "line", "overlay", "#dc2626"),
                output_descriptor("long_45", "line", "overlay", "#dc2626"),
                output_descriptor("long_50", "line", "overlay", "#dc2626"),
                output_descriptor("long_60", "line", "overlay", "#dc2626"),
            ],
        },
        period_descriptor("LINEAR_REG_FORECAST", "LINEAR REG FORECAST", "Statistical", "overlay", 14),
        period_descriptor("LINEAR_REG_INTERCEPT", "LINEAR REG INTERCEPT", "Statistical", "overlay", 14),
        IndicatorDescriptor {
            kind: "ANCHORED_VWAP",
            name: "ANCHORED VWAP",
            category: "Volume",
            pane: "overlay",
            params: vec![ParamDescriptor {
                name: "anchor",
                label: "Anchor Bar",
                default: 0.0,
                min: 0.0,
                step: "1",
            }],
            outputs: vec![output_descriptor("value", "line", "overlay", "#0f766e")],
        },
        IndicatorDescriptor {
            kind: "TYPICAL_PRICE",
            name: "TYPICAL PRICE",
            category: "Averages/Bands",
            pane: "overlay",
            params: Vec::new(),
            outputs: vec![output_descriptor("value", "line", "overlay", "#64748b")],
        },
        IndicatorDescriptor {
            kind: "WEIGHTED_CLOSE",
            name: "WEIGHTED CLOSE",
            category: "Averages/Bands",
            pane: "overlay",
            params: Vec::new(),
            outputs: vec![output_descriptor("value", "line", "overlay", "#64748b")],
        },
        IndicatorDescriptor {
            kind: "MA_CROSS",
            name: "MOVING AVERAGE CROSS",
            category: "Averages/Bands",
            pane: "overlay",
            params: vec![
                ParamDescriptor {
                    name: "fast",
                    label: "Fast",
                    default: 10.0,
                    min: 1.0,
                    step: "1",
                },
                ParamDescriptor {
                    name: "slow",
                    label: "Slow",
                    default: 20.0,
                    min: 2.0,
                    step: "1",
                },
            ],
            outputs: vec![
                output_descriptor("fast", "line", "overlay", "#059669"),
                output_descriptor("slow", "line", "overlay", "#dc2626"),
                output_descriptor("histogram", "histogram", "separate", "#86efac"),
            ],
        },
        IndicatorDescriptor {
            kind: "RAINBOW_MA",
            name: "RAINBOW MOVING AVERAGE",
            category: "Averages/Bands",
            pane: "overlay",
            params: vec![ParamDescriptor {
                name: "period",
                label: "Period",
                default: 2.0,
                min: 1.0,
                step: "1",
            }],
            outputs: vec![
                output_descriptor("r1", "line", "overlay", "#dc2626"),
                output_descriptor("r2", "line", "overlay", "#ea580c"),
                output_descriptor("r3", "line", "overlay", "#f59e0b"),
                output_descriptor("r4", "line", "overlay", "#84cc16"),
                output_descriptor("r5", "line", "overlay", "#059669"),
                output_descriptor("r6", "line", "overlay", "#0891b2"),
                output_descriptor("r7", "line", "overlay", "#2563eb"),
                output_descriptor("r8", "line", "overlay", "#7c3aed"),
                output_descriptor("r9", "line", "overlay", "#c026d3"),
                output_descriptor("r10", "line", "overlay", "#9333ea"),
            ],
        },
        IndicatorDescriptor {
            kind: "PRIME_NUMBER_BANDS",
            name: "PRIME NUMBER BANDS",
            category: "Support/Resistance",
            pane: "overlay",
            params: Vec::new(),
            outputs: vec![
                output_descriptor("upper", "line", "overlay", "#059669"),
                output_descriptor("lower", "line", "overlay", "#dc2626"),
            ],
        },
        period_descriptor("TIME_SERIES_FORECAST", "TIME SERIES FORECAST", "Statistical", "overlay", 14),
        IndicatorDescriptor {
            kind: "VALUATION_LINES",
            name: "VALUATION LINES",
            category: "Statistical",
            pane: "overlay",
            params: vec![
                ParamDescriptor {
                    name: "period",
                    label: "Period",
                    default: 20.0,
                    min: 1.0,
                    step: "1",
                },
                ParamDescriptor {
                    name: "multiplier",
                    label: "Offset %",
                    default: 5.0,
                    min: 0.1,
                    step: "0.1",
                },
            ],
            outputs: vec![
                output_descriptor("upper", "line", "overlay", "#059669"),
                output_descriptor("middle", "line", "overlay", "#2563eb"),
                output_descriptor("lower", "line", "overlay", "#dc2626"),
            ],
        },
        // ─── Compare category ──────────────────────────────────────
        period_descriptor("BETA", "BETA", "Compare", "separate", 20),
        period_descriptor("CORRELATION_COEFFICIENT", "CORRELATION COEFFICIENT", "Statistical", "separate", 14),
        IndicatorDescriptor {
            kind: "PERFORMANCE_INDEX",
            name: "PERFORMANCE INDEX",
            category: "Compare",
            pane: "separate",
            params: Vec::new(),
            outputs: vec![output_descriptor("value", "line", "separate", "#2563eb")],
        },
        period_descriptor("PRICE_RELATIVE", "PRICE RELATIVE", "Compare", "separate", 14),
        // ─── Momentum/Oscillator (new) ────────────────────────────────
        IndicatorDescriptor {
            kind: "AWESOME_OSCILLATOR",
            name: "AWESOME OSCILLATOR",
            category: "Momentum/Oscillator",
            pane: "separate",
            params: Vec::new(),
            outputs: vec![output_descriptor("value", "histogram", "separate", "#2563eb")],
        },
        IndicatorDescriptor {
            kind: "BOLLINGER_PCT_B",
            name: "BOLLINGER %B",
            category: "Momentum/Oscillator",
            pane: "separate",
            params: vec![
                ParamDescriptor { name: "period", label: "Period", default: 20.0, min: 1.0, step: "1" },
                ParamDescriptor { name: "multiplier", label: "Multiplier", default: 2.0, min: 0.1, step: "0.1" },
            ],
            outputs: vec![output_descriptor("value", "line", "separate", "#9333ea")],
        },
        period_descriptor("CENTER_OF_GRAVITY", "CENTER OF GRAVITY", "Momentum/Oscillator", "separate", 10),
        period_descriptor("CHANDE_FORECAST", "CHANDE FORECAST OSCILLATOR", "Momentum/Oscillator", "separate", 14),
        period_descriptor("CHANDE_MOMENTUM", "CHANDE MOMENTUM OSCILLATOR", "Momentum/Oscillator", "separate", 14),
        IndicatorDescriptor {
            kind: "COPPOCK_CURVE",
            name: "COPPOCK CURVE",
            category: "Momentum/Oscillator",
            pane: "separate",
            params: Vec::new(),
            outputs: vec![output_descriptor("value", "line", "separate", "#2563eb")],
        },
        period_descriptor("DISPARITY_INDEX", "DISPARITY INDEX", "Momentum/Oscillator", "separate", 14),
        period_descriptor("EASE_OF_MOVEMENT", "EASE OF MOVEMENT", "Momentum/Oscillator", "separate", 14),
        IndicatorDescriptor {
            kind: "EHLER_FISHER",
            name: "EHLER FISHER TRANSFORM",
            category: "Momentum/Oscillator",
            pane: "separate",
            params: vec![ParamDescriptor { name: "period", label: "Period", default: 10.0, min: 2.0, step: "1" }],
            outputs: vec![
                output_descriptor("fisher", "line", "separate", "#2563eb"),
                output_descriptor("trigger", "line", "separate", "#dc2626"),
            ],
        },
        IndicatorDescriptor {
            kind: "ELDER_RAY",
            name: "ELDER RAY INDEX",
            category: "Momentum/Oscillator",
            pane: "separate",
            params: vec![ParamDescriptor { name: "period", label: "Period", default: 13.0, min: 1.0, step: "1" }],
            outputs: vec![
                output_descriptor("bull", "histogram", "separate", "#059669"),
                output_descriptor("bear", "histogram", "separate", "#dc2626"),
            ],
        },
        IndicatorDescriptor {
            kind: "FRACTAL_CHAOS_OSCILLATOR",
            name: "FRACTAL CHAOS OSCILLATOR",
            category: "Momentum/Oscillator",
            pane: "separate",
            params: Vec::new(),
            outputs: vec![output_descriptor("value", "histogram", "separate", "#2563eb")],
        },
        IndicatorDescriptor {
            kind: "GATOR_OSCILLATOR",
            name: "GATOR OSCILLATOR",
            category: "Momentum/Oscillator",
            pane: "separate",
            params: Vec::new(),
            outputs: vec![
                output_descriptor("upper", "histogram", "separate", "#059669"),
                output_descriptor("lower", "histogram", "separate", "#dc2626"),
            ],
        },
        period_descriptor("INTRADAY_MOMENTUM", "INTRADAY MOMENTUM INDEX", "Momentum/Oscillator", "separate", 14),
        period_descriptor("LINEAR_REG_SLOPE", "LINEAR REG SLOPE", "Statistical", "separate", 14),
        period_descriptor("MA_DEVIATION", "MOVING AVERAGE DEVIATION", "Momentum/Oscillator", "separate", 20),
        period_descriptor("PRETTY_GOOD_OSCILLATOR", "PRETTY GOOD OSCILLATOR", "Momentum/Oscillator", "separate", 14),
        IndicatorDescriptor {
            kind: "PRICE_MOMENTUM_OSCILLATOR",
            name: "PRICE MOMENTUM OSCILLATOR",
            category: "Momentum/Oscillator",
            pane: "separate",
            params: vec![
                ParamDescriptor { name: "period", label: "Smoothing", default: 35.0, min: 1.0, step: "1" },
                ParamDescriptor { name: "smooth", label: "Double Smooth", default: 20.0, min: 1.0, step: "1" },
            ],
            outputs: vec![output_descriptor("value", "line", "separate", "#2563eb")],
        },
        IndicatorDescriptor {
            kind: "PRICE_OSCILLATOR",
            name: "PRICE OSCILLATOR",
            category: "Momentum/Oscillator",
            pane: "separate",
            params: vec![
                ParamDescriptor { name: "fast", label: "Fast", default: 12.0, min: 1.0, step: "1" },
                ParamDescriptor { name: "slow", label: "Slow", default: 26.0, min: 2.0, step: "1" },
            ],
            outputs: vec![output_descriptor("value", "line", "separate", "#2563eb")],
        },
        period_descriptor("RAINBOW_OSCILLATOR", "RAINBOW OSCILLATOR", "Momentum/Oscillator", "separate", 2),
        IndicatorDescriptor {
            kind: "RAVI",
            name: "RAVI",
            category: "Momentum/Oscillator",
            pane: "separate",
            params: vec![
                ParamDescriptor { name: "period", label: "Short", default: 7.0, min: 1.0, step: "1" },
                ParamDescriptor { name: "stoch_period", label: "Long", default: 65.0, min: 2.0, step: "1" },
            ],
            outputs: vec![output_descriptor("value", "line", "separate", "#2563eb")],
        },
        IndicatorDescriptor {
            kind: "RELATIVE_VIGOR",
            name: "RELATIVE VIGOR INDEX",
            category: "Momentum/Oscillator",
            pane: "separate",
            params: vec![ParamDescriptor { name: "period", label: "Period", default: 10.0, min: 1.0, step: "1" }],
            outputs: vec![
                output_descriptor("value", "line", "separate", "#2563eb"),
                output_descriptor("signal", "line", "separate", "#dc2626"),
            ],
        },
        IndicatorDescriptor {
            kind: "SCHAFF_TREND_CYCLE",
            name: "SCHAFF TREND CYCLE",
            category: "Momentum/Oscillator",
            pane: "separate",
            params: vec![
                ParamDescriptor { name: "fast", label: "Fast", default: 23.0, min: 1.0, step: "1" },
                ParamDescriptor { name: "slow", label: "Slow", default: 50.0, min: 2.0, step: "1" },
                ParamDescriptor { name: "stoch_period", label: "Cycle", default: 10.0, min: 1.0, step: "1" },
            ],
            outputs: vec![output_descriptor("value", "line", "separate", "#2563eb")],
        },
        IndicatorDescriptor {
            kind: "STOCHASTIC_MOMENTUM",
            name: "STOCHASTIC MOMENTUM INDEX",
            category: "Momentum/Oscillator",
            pane: "separate",
            params: vec![
                ParamDescriptor { name: "period", label: "Period", default: 13.0, min: 1.0, step: "1" },
                ParamDescriptor { name: "smooth", label: "Smooth", default: 3.0, min: 1.0, step: "1" },
            ],
            outputs: vec![output_descriptor("value", "line", "separate", "#2563eb")],
        },
        IndicatorDescriptor {
            kind: "SWING_INDEX",
            name: "SWING INDEX",
            category: "Momentum/Oscillator",
            pane: "separate",
            params: Vec::new(),
            outputs: vec![output_descriptor("value", "line", "separate", "#2563eb")],
        },
        period_descriptor("TREND_INTENSITY", "TREND INTENSITY INDEX", "Momentum/Oscillator", "separate", 14),
        IndicatorDescriptor {
            kind: "VOLUME_OSCILLATOR",
            name: "VOLUME OSCILLATOR",
            category: "Momentum/Oscillator",
            pane: "separate",
            params: vec![
                ParamDescriptor { name: "fast", label: "Fast", default: 5.0, min: 1.0, step: "1" },
                ParamDescriptor { name: "slow", label: "Slow", default: 10.0, min: 2.0, step: "1" },
            ],
            outputs: vec![output_descriptor("value", "line", "separate", "#2563eb")],
        },
        // ─── Money Flow (new) ─────────────────────────────────────────
        IndicatorDescriptor {
            kind: "KLINGER_VOLUME",
            name: "KLINGER VOLUME OSCILLATOR",
            category: "Money Flow",
            pane: "separate",
            params: Vec::new(),
            outputs: vec![output_descriptor("value", "line", "separate", "#2563eb")],
        },
        IndicatorDescriptor {
            kind: "MARKET_FACILITATION",
            name: "MARKET FACILITATION INDEX",
            category: "Money Flow",
            pane: "separate",
            params: Vec::new(),
            outputs: vec![output_descriptor("value", "line", "separate", "#9333ea")],
        },
        IndicatorDescriptor {
            kind: "NEGATIVE_VOLUME_INDEX",
            name: "NEGATIVE VOLUME INDEX",
            category: "Money Flow",
            pane: "separate",
            params: Vec::new(),
            outputs: vec![output_descriptor("value", "line", "separate", "#dc2626")],
        },
        IndicatorDescriptor {
            kind: "POSITIVE_VOLUME_INDEX",
            name: "POSITIVE VOLUME INDEX",
            category: "Money Flow",
            pane: "separate",
            params: Vec::new(),
            outputs: vec![output_descriptor("value", "line", "separate", "#059669")],
        },
        IndicatorDescriptor {
            kind: "PRICE_VOLUME_TREND",
            name: "PRICE VOLUME TREND",
            category: "Money Flow",
            pane: "separate",
            params: Vec::new(),
            outputs: vec![output_descriptor("value", "line", "separate", "#2563eb")],
        },
        IndicatorDescriptor {
            kind: "TRADE_VOLUME_INDEX",
            name: "TRADE VOLUME INDEX",
            category: "Money Flow",
            pane: "separate",
            params: Vec::new(),
            outputs: vec![output_descriptor("value", "line", "separate", "#0f766e")],
        },
        period_descriptor("TWIGGS_MONEY_FLOW", "TWIGGS MONEY FLOW", "Money Flow", "separate", 21),
        // ─── Projection (new) ─────────────────────────────────────────
        period_descriptor("PROJECTED_AGGREGATE_VOLUME", "PROJECTED AGGREGATE VOLUME", "Projection", "separate", 24),
        period_descriptor("PROJECTED_VOLUME_AT_TIME", "PROJECTED VOLUME AT TIME", "Projection", "separate", 24),
        // ─── Statistical (new) ────────────────────────────────────────
        period_descriptor("HISTORICAL_VOLATILITY", "HISTORICAL VOLATILITY", "Statistical", "separate", 20),
        period_descriptor("LINEAR_REG_R2", "LINEAR REG R2", "Statistical", "separate", 14),
        IndicatorDescriptor {
            kind: "PRIME_NUMBER_OSCILLATOR",
            name: "PRIME NUMBER OSCILLATOR",
            category: "Statistical",
            pane: "separate",
            params: Vec::new(),
            outputs: vec![output_descriptor("value", "histogram", "separate", "#2563eb")],
        },
        IndicatorDescriptor {
            kind: "RANDOM_WALK_INDEX",
            name: "RANDOM WALK INDEX",
            category: "Statistical",
            pane: "separate",
            params: vec![ParamDescriptor { name: "period", label: "Period", default: 14.0, min: 2.0, step: "1" }],
            outputs: vec![
                output_descriptor("high", "line", "separate", "#059669"),
                output_descriptor("low", "line", "separate", "#dc2626"),
            ],
        },
        // ─── Support/Resistance (new) ──────────────────────────────────
        IndicatorDescriptor {
            kind: "DARVAS_BOX",
            name: "DARVAS BOX",
            category: "Support/Resistance",
            pane: "overlay",
            params: Vec::new(),
            outputs: vec![
                output_descriptor("top", "line", "overlay", "#059669"),
                output_descriptor("bottom", "line", "overlay", "#dc2626"),
            ],
        },
        IndicatorDescriptor {
            kind: "VOLUME_PROFILE",
            name: "VOLUME PROFILE",
            category: "Support/Resistance",
            pane: "overlay",
            params: vec![ParamDescriptor { name: "period", label: "Period", default: 24.0, min: 2.0, step: "1" }],
            outputs: vec![
                output_descriptor("poc", "line", "overlay", "#2563eb"),
                output_descriptor("vah", "line", "overlay", "#059669"),
                output_descriptor("val", "line", "overlay", "#dc2626"),
            ],
        },
    ]
}
